config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :questionnaire do
    resources :question

    post '/answer', to: 'questionnaire#answer', as: :answer

    get '/report', to: 'report#show'
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers

  belongs_to :questionnaire

  serialize :common_answers, Hash

  attr_accessor :setting_answers
end

app/models/questionnaire.rb
class Questionnaire < ActiveRecord::Base
  has_many :questions

  validates :name, presence: true
  validates :questionnaire_type, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/question_controller.rb
class QuestionController < ApplicationController
  def new
    @command = Question.new

    @questionnaire = Questionnaire.find(params[:questionnaire_id])
  end

  def create
    @command = Question.new(params[:question].permit!)

    Questionnaire.find(params[:questionnaire_id]).questions.append(@command)

    unless @command.valid?
      @questionnaire = Questionnaire.find(params[:questionnaire_id])

      render :new and return
    end

    @command.save

    redirect_to questionnaire_path(params[:questionnaire_id])
  end
end

app/controllers/questionnaire_controller.rb
class QuestionnaireController < ApplicationController
  helper_method :answer_colour

  def index
    @questionnaires = Questionnaire.all
  end

  def new
    @command = Questionnaire.new
  end

  def create
    @questionnaire = Questionnaire.new(params[:questionnaire].permit!)

    unless @questionnaire.valid?
      render :new and return
    end

    @questionnaire.save

    redirect_to questionnaire_index_path
  end

  def show
    @questionnaire = Questionnaire.find(params[:id])

    @question = @questionnaire.questions.first

    colours = @question.last_colour.slice(/[0-9,]+/).split(',').map(&:to_i)
    @last_colour = colours[0] == 0 ? 256 + colours[1] : 256 - colours[0]
    #render text: @question.last_colour and return
    #render text: @last_colour and return

    @command = Answer.new(question_id: @question.id, when: Date.today)
  end

  def answer
    @command = Answer.new(params[:answer].permit!)

    question = Question.find(@command.question_id)

    if question.common_answers[@command.answer].nil?
      question.common_answers[@command.answer] = {
          frequency: 0,
          colour: ""
      }
    end

    question.common_answers[@command.answer][:frequency] += 1
    question.common_answers[@command.answer][:colour] = @command.colour

    @command.save
    question.save

    redirect_to questionnaire_path(question.questionnaire_id)
  end

  def answer_colour(colour)
    split = colour.slice(/[0-9,]+/).split(',').map(&:to_i)

    split[0] == 0 ? 256 + split[1] : 256 - split[0]
  end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  def show
    @questionnaire = Questionnaire.find(params[:questionnaire_id])

    answer_dates = @questionnaire.questions.flat_map { |q| q.answers.map(&:when) }

    @start_date = answer_dates.min.to_date
    @end_date = answer_dates.max.to_date
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmallVictories</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/question/new.html.erb
<%= form_for @command, url: questionnaire_question_index_path(questionnaire_id: @questionnaire.id) do |f| %>
    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <%= label :question, "Question" %>
          <%= f.text_field :question, class: 'form-control', required: true %>
        </div>

        <div class="form-group">
          <%= label :question_type, "Type" %>
          <%= f.select :question_type, options_for_select([["Drop down answers", :drop_down_answers], ["Open answer", :open_answer], ["Scale", :scale]]), class: 'form-control'%>
        </div>

        <%= submit_tag("Create", class: "btn btn-primary", data: { disable_with: "Creating..." }) %>
      </div>
    </div>
<% end %>

app/views/questionnaire/index.html.erb
Index page<br />

<%= link_to "New Questionnaire", new_questionnaire_path %><br /><br />

<% @questionnaires.each do |questionnaire| %>
    <%= link_to questionnaire.name, questionnaire_path(questionnaire) %><br />
<% end %>

app/views/questionnaire/new.html.erb
<%= form_for @command, url: questionnaire_index_path do |f| %>
    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <%= label :name, "Name" %>
          <%= f.text_field :name, class: 'form-control', required: true %>
        </div>

        <div class="form-group">
          <%= label :questionnaire_type, "Type" %>
          <%= f.select :questionnaire_type, options_for_select(["Productivity"]), class: 'form-control'%>
        </div>

        <%= submit_tag("Create", class: "btn btn-primary", data: { disable_with: "Creating..." }) %>
      </div>
    </div>
<% end %>

app/views/questionnaire/show.html.erb
Show page<br />

<%= @question.question %>

<%= form_for @command, url: questionnaire_answer_path(questionnaire_id: @questionnaire.id) do |f| %>
    <%= f.hidden_field(:question_id) %>
    <%= f.hidden_field(:when) %>

    <%= label_tag(:when) %>
    <%= f.select(:when, options_for_select((-30..30).map{|num| Date.today + num})) %>

    <% case @question.question_type.to_sym
         when :drop_down_answers %>
        <%= f.text_field(:answer, list: 'drop_down_answers') %>
        <datalist id="drop_down_answers">
          <% @question.common_answers.each do |answer| %>
          <option data-colour="<%= answer_colour(answer[1][:colour]) %>"><%= answer[0] %></option>
          <% end %>
        </datalist>
      <% when :open_answer %>
        Open answer
      <% when :scale %>
        Scale
    <% end %>

    Colour?
    <input name="scale" type="range" value="<%= @last_colour %>" min="0" max="512" />
    <div id="scale-colour" style="width: 20px; height: 20px; position:relative; background-color: red;"></div>
    <input type="hidden" name="answer[colour]">

    <%= submit_tag("Answer", class: "btn btn-primary", data: { disable_with: "Answering..." }) %>
<% end %>

<%= link_to "New Question", new_questionnaire_question_path(@questionnaire) %>

<script>
  var $scale = $("[name=scale]");
  var $scaleColour = $("#scale-colour");
  var $colour = $("[name='answer[colour]']");
  var $answer = $("#answer_answer");

  var updateColour = function(){
    var red, green;
    var val = $scale.val();

    if(val <= 256) {
      red = 256;
      green = val;
    }else{
      red = 512 - val;
      green = 256;
    }

    $scaleColour.css('background-color', "rgb(" + red + "," + green + ",0)");
    $colour.val("rgb(" + red + "," + green + ",0)");
  };

  $answer.on('input change', function(){
    var val = $(this).val();

    var $dataList = $("datalist > option").filter(function(){
      return $(this).text() == val;
    });
    $scale.val($dataList.data("colour"));
    updateColour();
  });

  $scale.on('input change', updateColour);

  updateColour();
</script>

app/views/report/show.html.erb
<h1><%= @questionnaire.name %></h1>

<table>
  <thead>
  <tr>
    <th><div>Date</div></th>
    <% @questionnaire.questions.each do |question| %>
    <th>
      <div><%= question.question %></div>
    </th>
    <% end %>
  </tr>
  </thead>

  <tbody>
  <% (@start_date..@end_date).each do |date| %>
  <tr>
    <td><%= date %></td>
    <% @questionnaire.questions.each do |question|
      answer = question.answers.select { |a| a.when.to_date == date }.first %>
    <td class="answer" style="background-color: <%= answer ? answer.colour : "rgb(256,256,256)" %>"></td>
    <% end %>
  </tr>
  <% end %>
  </tbody>
</table>

<style>
  .answer {
    width: 20px;
    height: 20px;
    border: 1px solid #CCC;
  }

    th {
      white-space: nowrap;
    }

    th > div {
      transform: translate(5px, -9px) rotate(315deg);
      width: 20px;
    }
</style>